name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build & Unit Tests
      run: ./gradlew testDebugUnitTest --warning-mode all --stacktrace

    - name: Run Instrumented Tests on Emulator (API 35)
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        target: google_apis
        arch: x86_64
        profile: pixel_4
        ram-size: 4096M
        disk-size: 6000M
        script: ./gradlew connectedDebugAndroidTest
